name: iHMNNF
channels:
    - pytorch
    - anaconda
    - menpo
    - conda-forge
dependencies:
    - python=3.6.13
    - pip=21.2.2
    - numpy=1.19.2
    - pandas=1.1.5
    - optuna=2.10.0
    - tensorflow=2.2.0
    - keras=2.3.1
    - sqlalchemy=1.4.22
    - seaborn=0.11.2
    - scikit-learn=0.24.2
    - pymongo=3.12.0
    - matplotlib=3.2.2
    - cx_oracle=8.2.1
